# Đào Duy Tùng - 2033364
version: "3.1"
name: lap-trinh-nang-cao
services:
  mongo:
    image: mongo
    restart: unless-stopped
    
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE : lap-trinh-nang-cao

  api:
    build:
      context: ./saoke03
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3002:3000
    environment:
      GITHUB_CLIENT_ID: XXXXXXX
      GITHUB_CLIENT_SECRET: XXXXXXX
      NEXTAUTH_SECRET: your_random_secret_key
      NEXTAUTH_URL: http://localhost:3002
      MONGODB_URI: mongodb://root:123456@mongo:27017/lap-trinh-nang-cao?authSource=admin
    depends_on:
      - mongo
